plugins {
    id 'war'
    id 'java'
}

apply plugin: 'war'

group 'lk.cab.manager'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.10.0'
}

sourceCompatibility = '11'
targetCompatibility = '11'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

task stage {
    dependsOn build
}

dependencies {
    compileOnly('jakarta.servlet:jakarta.servlet-api:6.0.0')

    // https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
    implementation group: 'com.mysql', name: 'mysql-connector-j', version: '9.1.0'

    implementation(group: 'com.heroku', name: 'webapp-runner', version: '10.1.34.0') {
//        exclude group: 'org.apache.tomcat.embed', module: 'tomcat-embed-websocket'
        exclude group: 'org.apache.tomcat.embed'
//        exclude group: 'org.apache.tomcat'
    }
}

test {
    useJUnitPlatform()
}

task copyWebAppRunner(type: Copy) {
    // Improved find method to handle nulls and empty collections
    def webappRunnerJar = configurations.runtimeClasspath.find { it.name.startsWith('webapp-runner') }

    if (webappRunnerJar != null) { // Check if found
        from webappRunnerJar
        into "$buildDir/webapp-runner"
    } else {
        println "WARNING: webapp-runner.jar not found in runtimeClasspath.  Build might fail on Heroku."
        // You might consider throwing an exception here to halt the build if webapp-runner is crucial.
        // throw new GradleException("webapp-runner.jar not found.")
    }

}

war {
    dependsOn copyWebAppRunner // Make the war task depend on copying the webapp-runner
}