plugins {
    id 'war'
    id 'java'
}

group 'lk.cab.manager'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.10.0'
}

sourceCompatibility = '11'
targetCompatibility = '11'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

task stage {
    dependsOn build
}

dependencies {
    compileOnly('jakarta.servlet:jakarta.servlet-api:6.0.0')

    // https://mvnrepository.com/artifact/com.mysql/mysql-connector-j
    implementation group: 'com.mysql', name: 'mysql-connector-j', version: '9.1.0'

    implementation 'com.heroku:webapp-runner:9.0.52.0'

    testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
    useJUnitPlatform()
}

war {
    archiveFileName = "app.war"
}
